---
title: "Pedigree biuld-up"
output: html_notebook
---

# Load Libraries
```{r}
options(warn=-1)
library(tidyverse)
library(bigrquery)
library(lubridate)
library(statar)
library(knitr)
library(stringi)
library(broom)
library(ggrepel)
library(ggfortify)
library(ggroups)

setwd("C:/Users/victo/Box/dairy_matching/code/AISS data")
```


# NAAB Info dataset
```{r}
projectid <- "dairy-168114"
query <- "
SELECT
    reg_id,
    id_number,
    breed,
    country,
    primary_naab_code,
    naab_codes,
    reg_name,
    birthdate,
    semen_release_date,
    genotype_information,
    sire_breed,
    sire_country,
    sire_id_number,
    dam_breed,
    dam_country,
    dam_id_number,
    mgs_breed,
    mgs_country,
    mgs_id_number,
    status
FROM
    CDCB_data.NAAB_Info
"

naab <- bq_project_query(projectid, query)
naab <- bq_table_download(naab)

naab <- naab |>
  mutate(birthdate = mdy(birthdate),
         yob = year(birthdate))

naab <- naab |>
  mutate(id_number = stringr::str_replace(id_number, "\\.", ""),
         id_number = str_pad(id_number, width = 12, side = "left", pad = "0"),
         reg_id = paste0(breed, country, id_number))

naab <- naab |>
  mutate(sire_id_number = stringr::str_replace(sire_id_number, "\\.", ""),
         sire_id_number = str_pad(sire_id_number, width = 12, side = "left", pad = "0"),
         sire_id = paste0(sire_breed, sire_country, sire_id_number))

naab$sire_id <- replace(naab$sire_id, naab$sire_id == "NANANA", NA)

naab <- naab |>
  mutate(mgs_id_number = stringr::str_replace(mgs_id_number, "\\.", ""),
         mgs_id_number = str_pad(mgs_id_number, width = 12, side = "left", pad = "0"),
         mgs_id = paste0(mgs_breed, mgs_country, mgs_id_number))

naab$mgs_id <- replace(naab$mgs_id, naab$mgs_id == "NANANA", NA)

naab <- naab |>
  mutate(dam_id_number = stringr::str_replace(dam_id_number, "\\.", ""),
         dam_id_number = str_pad(dam_id_number, width = 12, side = "left", pad = "0"),
         dam_id = paste0(dam_breed, dam_country, dam_id_number))

naab$dam_id <- replace(naab$dam_id, naab$dam_id == "NANANA", NA)
```


# Inactive Sires data
```{r}
naab_old <- read_csv("../../data/old_evals_clean.csv")
```
```{r}
library(ggroups)
library(pedtools)

naab_ped <- naab[!duplicated(naab$reg_id),]

naab_ped <- naab_ped |>
  select(c(reg_id, sire_id, dam_id)) |>
  data.frame()

#pedcheck(naab_ped)
naab_ped <- naab_ped |> 
  dplyr::select(c(reg_id, sire_id, dam_id)) 

naab_ped[is.na(naab_ped)] <- 0
naab_ped <- renum(naab_ped)
```
```{r}
library(Matrix)
Amat <- readMM("../../data/A_mat.mtx")
```

```{r}
Amat <- buildA(naab_ped$newped)
Amat[lower.tri(Amat)] <- NA
Amat <- as(Amat, "dgCMatrix")
```




Identifying lines
```{r}
connections <- naab[, c('reg_id', 'sire_id')] |>
  distinct(reg_id, .keep_all = TRUE)
names(connections) <- c("reg_id", "sire_id_g0")
connect <- naab[, c('reg_id', 'sire_id')] |>
  distinct(reg_id, .keep_all = TRUE)

cnt = 1
ix = 0

while(cnt != 0){
  connect_temp <- connect
  names(connect_temp) <- c(paste0('sire_id_g', as.character(ix)), paste0('sire_id_g', as.character(ix+1)))
  connections <- left_join(connections, connect_temp, by = paste0('sire_id_g', as.character(ix)))
  ix <- ix + 1
  cnt <- table(connections[, paste0('sire_id_g', as.character(ix))]) |>
    dim()
  print(cnt)
  rm(connect_temp)
}

connections <- connections[, -18]
rm(connect)
```


```{r}
connections |>
  pivot_longer(sire_id_g0:sire_id_g15, names_to = "generation", values_to = "sire_id") |>
  filter(!is.na(sire_id)) |>
  separate(generation, into = c("type", "id", "gen"), sep = "_") |>
  select(-c(type, id)) |>
  separate(gen, into = c("g_var", "gen_num"), sep = 1) |>
  select(-g_var) |>
  mutate(gen_num = as.numeric(gen_num)+1,
          weight = 2^(-(gen_num+1))) ->
  lines
```

