---
title: "Fixed Effects Models"
output: html_notebook
---

## Libraries and set working directory

```{r}
library(tidyverse)
library(lfe)
library(bigrquery)
library(lubridate)
library(statar)
library(gganimate)
library(stringi)
library(glmnet)
library(broom)
library(ggrepel)
library(ggfortify)
library(caret)
library(tikzDevice)

setwd("C:/Users/victo/Box/dairy_matching/code/AISS data")
```

## Google big query for PTAs
```{r}
projectid <- "dairy-168114"
query <- "SELECT
  country,
  id_number,
  name,
  primary_stud_code,
  reg_id,
  mgs_id,
  sire_id,
  period,
  status,
  naab_id,
  pta_milk_unadj as pta_milk,
  pta_fat_lb_unadj as pta_fat_lb,
  pta_protein_lb_unadj as pta_protein_lb,
  pta_scs_unadj as pta_scs,
  pta_pl_unadj as pta_pl,
  pta_dpr_unadj as pta_dpr,
  pta_hcr_unadj as pta_hcr,
  pta_ccr_unadj as pta_ccr,
  pta_liv_unadj as pta_liv,
  pta_ssb_unadj as pta_ssb,
  pta_dsb_unadj as pta_dsb,
  pta_type_unadj as pta_type,
  pta_stature_unadj as pta_stature,
  pta_strength_unadj as pta_strength,
  pta_body_depth_unadj as pta_body_depth,
  pta_dairy_form_unadj as pta_dairy_form,
  pta_rump_angle_unadj as pta_rump_angle,
  pta_thurl_width_unadj as pta_thurl_width,
  pta_rear_legs_side_unadj as pta_rear_legs_side,
  pta_rear_legs_rear_unadj as pta_rear_legs_rear,
  pta_foot_angle_unadj as pta_foot_angle,
  pta_foot_leg_score_unadj as pta_foot_leg_score,
  pta_fore_udder_unadj as pta_fore_udder,
  pta_rear_udder_height_unadj as pta_rear_udder_height,
  pta_rear_udder_width_unadj as pta_rear_udder_width,
  pta_udder_cleft_unadj as pta_udder_cleft,
  pta_udder_depth_unadj as pta_udder_depth,
  pta_teat_front_place_unadj as pta_teat_front_place,
  pta_teat_rear_place_unadj as pta_teat_rear_place,
  pta_teat_length_unadj as pta_teat_length,
  pta_mobility,
  pta_gest_length_unadj as pta_gest_length,
  pta_ketosis_unadj as pta_ketosis,
  pta_metritis_unadj as pta_metritis,
  pta_mastitis_unadj as pta_mastitis,
  pta_milk_fever_unadj as pta_milk_fever,
  FM_unadj as FM,
  CM_unadj as CM,
  GM_unadj as GM,
  NM_unadj as NM,
  TPI,
  udder_composite, 
  body_weight_composite,
  feet_legs_composite,
  aaa_rating,
  daughts_in_milk_pta,
  dob,
  semen_price
FROM
  CDCB_data.NAAB_AISS
WHERE 
  breed='HO'
"

naab <- bq_project_query(projectid, query)
naab <- bq_table_download(naab)
```

## Data preparation

```{r}
naab <- naab %>%
  separate(period, into = c("year", "per_num"), sep = "-", remove = FALSE)

## Some bulls have missing status
naab %>% 
  filter(is.na(status) == TRUE) %>%
  mutate(ndaugh = ifelse(daughts_in_milk_pta > 0, 1, 0)) %>%
  group_by(country, ndaugh) %>%
  tab(status)

naab <- naab %>%
  mutate(status_new = case_when(
    status == "A" ~ "active",
    status == "F" ~ "foreign",
    status == "G" ~ "genomic"
  ))

naab$status_new <- replace(naab$status_new, (is.na(naab$status_new) == TRUE) & 
                             !(naab$country %in% c("840", "USA")), "foreign")
naab$status_new <- replace(naab$status_new, (is.na(naab$status_new) == TRUE) & 
                             (naab$country %in% c("840", "USA")), "active")
```

## Companies data
```{r}
query <- "SELECT
  market_code,
  company_name,
  larger_company
FROM
  `dairy-168114.DHI_data.company_info`"

companies <- bq_project_query(projectid, query)
companies <- bq_table_download(companies)
```

## Merge datasets
```{r}
naab <- left_join(naab, companies, by = c("primary_stud_code" = "market_code"))
```

## Subset data

```{r}
bull_data <- naab %>%
  filter(year < 2013 & semen_price > 0 & semen_price != 999 & status_new != 'genomic') 
```

## Model 1: Company level and period FEs and PTAs
```{r}
model1 <- bull_data %>%
            felm(semen_price~pta_milk+pta_fat_lb+pta_protein_lb+pta_scs+
                           pta_pl+pta_dpr+pta_type+pta_stature+pta_strength+
                           pta_body_depth+daughts_in_milk_pta+pta_dairy_form+
                           pta_rump_angle+pta_thurl_width+pta_rear_legs_side+
                           pta_fore_udder+pta_rear_udder_height+
                           pta_rear_udder_width+pta_udder_cleft+pta_udder_depth+
                           pta_teat_front_place+pta_teat_length|factor(primary_stud_code)+factor(period)|0|0,
                 data = .)
summary(model1)
```

## Model 2: Bull-level and period FEs and PTAs
```{r}
model2 <- bull_data %>%
            felm(semen_price~pta_milk+pta_fat_lb+pta_protein_lb+pta_scs+
                           pta_pl+pta_dpr+pta_type+pta_stature+pta_strength+
                           pta_body_depth+daughts_in_milk_pta+pta_dairy_form+
                           pta_rump_angle+pta_thurl_width+pta_rear_legs_side+
                           pta_fore_udder+pta_rear_udder_height+
                           pta_rear_udder_width+pta_udder_cleft+pta_udder_depth+
                           pta_teat_front_place+pta_teat_length|factor(reg_id)+factor(period)|0|0,
                 data = .)
summary(model2)
```

## Model 3: Bull-level FEs and PTAs
```{r}
model3 <- bull_data %>%
            felm(semen_price~pta_milk+pta_fat_lb+pta_protein_lb+pta_scs+
                           pta_pl+pta_dpr+pta_type+pta_stature+pta_strength+
                           pta_body_depth+daughts_in_milk_pta+pta_dairy_form+
                           pta_rump_angle+pta_thurl_width+pta_rear_legs_side+
                           pta_fore_udder+pta_rear_udder_height+
                           pta_rear_udder_width+pta_udder_cleft+pta_udder_depth+
                           pta_teat_front_place+pta_teat_length|factor(reg_id)|0|0,
                 data = .)
summary(model3)
```
```{r}
model35 <- bull_data %>%
            felm(semen_price~pta_milk+pta_fat_lb+pta_protein_lb+pta_scs+
                           pta_pl+pta_dpr+pta_type+pta_stature+pta_strength+
                           pta_body_depth+daughts_in_milk_pta+pta_dairy_form+
                           pta_rump_angle+pta_thurl_width+pta_rear_legs_side+
                           pta_fore_udder+pta_rear_udder_height+
                           pta_rear_udder_width+pta_udder_cleft+pta_udder_depth+
                           pta_teat_front_place+pta_teat_length|0|0|0,
                 data = .)
summary(model35)
```

## Model 4: Bull-level FEs
```{r}
model4 <- bull_data %>%
            lm(semen_price~factor(reg_id),
                 data = .)
glance(model4)
```

## Model 5: Bull-level and period-level FEs
```{r}
model5 <- bull_data %>%
            lm(semen_price~factor(reg_id)+factor(period),
                 data = .)
glance(model5)
```

## Model 6: PTAs + Bull FE
```{r}
model6 <- bull_data %>%
            lm(semen_price~factor(reg_id) + pta_milk+pta_fat_lb+pta_protein_lb+pta_scs+
                           pta_pl+pta_dpr+pta_type+pta_stature+pta_strength+
                           pta_body_depth+daughts_in_milk_pta+pta_dairy_form+
                           pta_rump_angle+pta_thurl_width+pta_rear_legs_side+
                           pta_fore_udder+pta_rear_udder_height+
                           pta_rear_udder_width+pta_udder_cleft+pta_udder_depth+
                            pta_teat_front_place+pta_teat_length, data = .)
glance(model6)
```


```{r}
model7 <- bull_data %>%
            lm(semen_price~factor(mgs_id) + factor(sire_id), data = .)
glance(model7)
```
